name: pubsub-c

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cd tests && make all
    - name: Run tests
      run: cd tests && ./tests.out
    - name: Get Covarage Tests
      run: cd tests && gcov ./tests.out
    - name: Get Covarage Pubsub
      run: cd tests && gcov pubsub.c
